### ISSUE TITLE
Desarrollar front-end de la portada

### ISSUE THREAD

**Issue by pgarciagon** [bloque64/bloque64_web#6]

**Comment by DiazRock** [comment]
![image](https://user-images.githubusercontent.com/50834033/80867875-a1f49380-8c64-11ea-873d-b745ad0319b1.png)

**Comment by DiazRock** [comment]
@pgarciagon , cuál es la idea con la lupa?

**Comment by DiazRock** [comment]
La señalé ahí de alguna forma...

**Comment by msftguille** [comment]
Saludos chicos, espero que estén muy bien, ya tengo el trabajo del post más predominante (index 1) y post un poco menos predominante (index 2-3) listos, estaré haciendo el push a más tardar el día de mañana Lunes.

Hoy no sé si pueda estar en la reunión, porque mi internet está sumamente terrible, acá por donde vivo hay problemas fuertes, porque vivo cerca de un barrio donde van 2 días en un conflicto armado, tanto que balas perdidas han impactado edificios cercanos al mío y hemos tenido que mantenernos en resguardo y las conexiones han fallado terriblemente.

Sin embargo, estaré colocando por acá las capturas de las vistas previas de los elementos para que me vayan dando feedback, estamos en contacto.

**Comment by pgarciagon** [comment]
@DiazRock La idea con la lupa es una opción de búsqueda en todo el periódico. Se introduce el texto y se devuelve una lista de artículos ordenados por relevancia que contengan el texto introducido

**Comment by pgarciagon** [comment]
> Saludos chicos, espero que estén muy bien, ya tengo el trabajo del post más predominante (index 1) y post un poco menos predominante (index 2-3) listos, estaré haciendo el push a más tardar el día de mañana Lunes.
> 
> Hoy no sé si pueda estar en la reunión, porque mi internet está sumamente terrible, acá por donde vivo hay problemas fuertes, porque vivo cerca de un barrio donde van 2 días en un conflicto armado, tanto que balas perdidas han impactado edificios cercanos al mío y hemos tenido que mantenernos en resguardo y las conexiones han fallado terriblemente.
> 
> Sin embargo, estaré colocando por acá las capturas de las vistas previas de los elementos para que me vayan dando feedback, estamos en contacto.

Vale, esperando las capturas y mantente a salvo: la seguridad ante nada.

**Comment by DiazRock** [comment]
> Saludos chicos, espero que estén muy bien, ya tengo el trabajo del post más predominante (index 1) y post un poco menos predominante (index 2-3) listos, estaré haciendo el push a más tardar el día de mañana Lunes.
> 
> Hoy no sé si pueda estar en la reunión, porque mi internet está sumamente terrible, acá por donde vivo hay problemas fuertes, porque vivo cerca de un barrio donde van 2 días en un conflicto armado, tanto que balas perdidas han impactado edificios cercanos al mío y hemos tenido que mantenernos en resguardo y las conexiones han fallado terriblemente.
> 
> Sin embargo, estaré colocando por acá las capturas de las vistas previas de los elementos para que me vayan dando feedback, estamos en contacto.

Cuídate, Ilaz. Estaré viendo en github lo que has hecho.

**Comment by pgarciagon** [comment]
He hecho un clone nuevo, checkout de DiazRock_Develop y al hacer un `npm install ` me da el siguiente error:

pgarcgos-MacBook-Pro:code pgarcgo$ npm install
npm WARN saveError ENOENT: no such file or directory, open '/Users/pgarcgo/code/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/pgarcgo/code/package.json'
npm WARN code No description
npm WARN code No repository field.
npm WARN code No README data
npm WARN code No license field.

up to date in 0.46s
found 0 vulnerabilities


No tendria que existir un `package.json` el el branch?

Saludos

**Comment by DiazRock** [comment]
Yo veo el package.json en el branch. a lo  mejor si haces git clone de nuevo. De ahí en adelante no sé mucho.

**Comment by DiazRock** [comment]
@pgarciagon 
![image](https://user-images.githubusercontent.com/50834033/82775475-d697dd00-9e15-11ea-959e-a27e42eda8c7.png)
Hice git clone y veo ahí el package.json

**Comment by DiazRock** [comment]
Ya publiqué un post acerca de esto, y hemos resuelto el problema de hacer upload del plugin (es lo que daba error). Voy a cerrar :)
